theme: minima
description: MAKE ART with Artificial Intelligence [https://www.amazon.com/dp/B08YXW7M9K](https://www.amazon.com/dp/B08YXW7M9K)
author: Kevin Ashley
layout: home
twitter_username: kashleytwit
github_username:  kevinash
instagram_username: awesomeai_art