theme: minima
description: MAKE ART with Artificial Intelligence - Tutorials and Code
author: Kevin Ashley
layout: home
twitter_username: kashleytwit
github_username:  kevinash
instagram_username: awesomeai_art